jobs:
  build:
    steps:
    - name: Setup Node.js
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test-external
      working-directory: ./rest