name: Pipeline Trabalho final API Rest - CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Run unit tests
      run: npm test

    - name: Start REST API
      run: npm run start-rest &
    
    - name: Wait for API
      run: sleep 5

    - name: Run external API tests
      run: npm run test-external

    - name: Install k6
      run: |
        sudo apt-get update
        sudo apt-get install -y gnupg2
        curl -s https://dl.k6.io/key.gpg | sudo apt-key add -
        echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
        sudo apt-get update
        sudo apt-get install -y k6

    - name: Run Performance Tests
      run: |
        export K6_WEB_DASHBOARD="true"
        export K6_WEB_DASHBOARD_EXPORT="dashboard.html"
        export K6_WEB_DASHBOARD_PERIOD="2s"
        k6 run test/k6/checkout.test.js